<?php
/**
 * Layout script: layout component # toolbars
 * @author khanhdtp 2016-06-26
 */
?>
<nav class="navbar navbar-default">
	<div class="container-fluid">

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
				    <a href="#"><i class="fa fa-link"></i> Link</a>
				</li>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>