<?php
/**
 * Script view: list account 
 * @author khanhdtp
 */
// Get Zend_Controller_Front;
$front = Zend_Controller_Front::getInstance();

// Toolbars
$this->Bt3NavLinks(array(
    $this->Bt3NavLinks()->iconNew(),
    $this->Bt3NavLinks()->iconDelete()
));
?>
<div class="card">
	<!-- card-header -->
	<div class="card-header">
		<?php
			// Filter form;
			echo $this->Bt3FilterForm()->render($this->form, $this->formSearch);
		?><br/>
		<h2>
			<small><?php
			  	echo $this->translate('Tổng số dòng') . ': ' . ($totalItemsCount = count($this->paginator)) . '.' 
			?></small>
		</h2>
	</div>
	<!-- ./card-header -->
	<form id="admin-form" class="card-body table-responsive" enctype="application/x-www-form-urlencoded" method="post" action="">
		<table id="tbl-data-list" class="table table-bordered table-condensed table-hover">
            <thead>
                <tr>
					<th width="10">#</th>
					<th width="10" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolCheckerToggler(); ?>
					</th>
					<th><?php echo $this->Bt3ManageTools()->mToolSorter($this->translate('Tên đăng nhập'), 'username'); ?></th>
					<th><?php echo $this->Bt3ManageTools()->mToolSorter($this->translate('Tên tài khoản'), 'fullname'); ?></th>
					<th width="10" class="nowrap"><?php echo $this->translate('Ảnh đại diện'); ?></th>
					<th><?php echo $this->translate('Ghi chú'); ?></th>
					<th><?php echo $this->translate('Nhóm tài khoản'); ?></th>
                    <th width="10"><?php echo $this->translate('K.Hoạt?'); ?></th>
					<th width="10"><?php echo $this->translate('Q.Lý?'); ?></th>
				</tr>
            </thead>
            <tbody>
        <?php
            if ($totalItemsCount):
				// Manage tools 
				$manageBtnLinks = array(
					'detail' => $this->Bt3ManageTools()->mBtnDetail(),
					'edit' => $this->Bt3ManageTools()->mBtnEdit(),
					'delete' => $this->Bt3ManageTools()->mBtnDelete(),
				);
                //
                $no = 0;
                //
                foreach ($this->paginator as $item):
        ?>
				<tr>
					<td align="center" class="nowrap"><?php echo ++$no; ?></td>
					<td align="center" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolChecker($item->id); ?>
					</td>
					<td><?php echo $item->username; ?></td>
					<td><?php echo $item->fullname; ?></td>
					<td align="center" class="nowrap">
						<?php 
							// Avatar
							echo ($avatar = $item->returnAvatarWebPath())
								? ("<a href=\"{$avatar}\" target=\"_blank\">"
									. "<img src=\"{$avatar}\" class=\"img-thumb img-thumb-32\" />"
								. "</a>")
								: ''
							; 
						?>
					</td>
					<td><?php echo $item->note; ?></td>
					<td><?php echo $this->groupOptions[$item->group_id]; ?></td>
					<td align="center" class="nowrap">
						<?php echo $this->Bt3ManageTools()->mToolActiveToggler($item->id, $item->active); ?>
					</td>
					<td class="nowrap">
					<?php
						$manageBtns = array(
							'__detail_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['detail']),
							'__update_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['edit']),
							'__delete_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['delete'])
						);
						echo implode("\n", $manageBtns);
					?>
					</td>
				</tr>
        <?php 
                endforeach;
            endif;
        ?>
			</tbody>
		</table>
	</form>
	<!-- /.box-body -->
	<div class="card-header clearfix">
        <div class="pull-right">
            <?php
                echo $this->paginationControl($this->paginator); 
            ?>
        </div>
	</div>
</div>
<?php
// CSS:
// +++ Inline style;
$this->HeadStyleAction($this->curRequest);

// CSS:
// +++ Inline script;
$this->HeadScriptAction($this->curRequest);