<?php
/**
 * Dashboard 
 */
// Widget
$widgets = (array)$this->widgets;
// 
$userRefs = (array)$this->userRefs;
// Language key
$lang = null;
?>
<div id="dashboard" class="dashboard row">
<?php
	foreach ($widgets as $widget):
		//
		$userRef = $userRefs[$wId = $widget->getId()];
		if (!empty($userRefs) && !$userRef) {
			continue;
		}
		// Widget's info
		$wgName = trim($widget->getName($lang));
		$wgNote = trim($widget->getNote($lang));
		$wgContent = '';
		if (!($wgContent = trim($widget->getContent()))) {
			try {
				$wgContent = $this->action($widget->getAction(), $widget->getController(), $widget->getModule(), $widget->getParams());
			} catch (Exception $e) {
				$wgContent = $e->getTraceAsString();
			}
		}
		if (!($wgContent = trim($wgContent))) {
			continue;
		}
?>
	<div class="db-widget col-xs-12 col-sm-<?php echo $userRef['size']; ?>" data-id="<?php echo $wId; ?>" data-offset="<?php echo $widget->getOffset(); ?>">
		<div class="card">
		<?php if ($wgName): ?>
			<div class="db-widget-header card-header"><h2>
				<?php echo $wgName; ?>
				<small><?php echo $widget->getNote(); ?></small>
			</h2></div>
		<?php endif; ?>
			<div class="db-widget-body card-body table-responsive">
			<?php
				if (!($content = trim($widget->getContent()))) {
					try {
						$content = $this->action($widget->getAction(), $widget->getController(), $widget->getModule(), $widget->getParams());
					} catch (Exception $e) {
						$content = $e->getTraceAsString();
					}
				}
				echo $content;
			?>
			</div>
			<div class="db-widget-footer card-footer text-right m-t-10">
				<button class="btn btn-primary bt-sm dbwidget-btn-minus">
					<span class="glyphicon glyphicon-minus"></span>
				</button>
				<button class="btn btn-primary bt-sm dbwidget-btn-plus">
					<span class="glyphicon glyphicon-plus"></span>
				</button>
				<button class="btn btn-danger bt-sm dbwidget-btn-left">
					<span class="glyphicon glyphicon-chevron-left"></span>
				</button>
				<button class="btn btn-danger bt-sm dbwidget-btn-right">
					<span class="glyphicon glyphicon-chevron-right"></span>
				</button>
			</div>
		</div>
	</div>
<?php
	endforeach; 
?>
</div> 
<?php
// CSS:
// +++ Inline style;
$this->HeadStyleAction($this->curRequest, array(), array(
	'action' => 'dashboard'
));

// CSS:
// +++ Inline script;
$this->HeadScriptAction($this->curRequest, array(), array(
	'action' => 'dashboard'
));