<?php
/**
 * Script view: layout component # left_sidebar
 * @author khanhdtp
 */
?>
<!-- Left side column. contains the logo and sidebar -->
<aside id="sidebar" class="sidebar c-overflow">
	<!-- profile sub_sidebar -->
	<div class="s-profile">
        <a href="#" data-ma-action="profile-menu-toggle">
            <div class="sp-pic">
                <img src="img/profile-pics/1.jpg" alt="">
            </div>
            <div class="sp-info">
                Malinda Hollaway
                <i class="zmdi zmdi-caret-down"></i>
            </div>
        </a>
        <ul class="main-menu">
            <li>
                <a href="profile-about.html"><i class="zmdi zmdi-account"></i> View Profile</a>
            </li>
            <li>
                <a href="#"><i class="zmdi zmdi-input-antenna"></i> Privacy Settings</a>
            </li>
            <li>
                <a href="#"><i class="zmdi zmdi-settings"></i> Settings</a>
            </li>
            <li>
                <a href="#"><i class="zmdi zmdi-time-restore"></i> Logout</a>
            </li>
        </ul>
    </div>
    <!-- ./profile sub_sidebar -->

	<!-- Sidebar Menu -->
	<?php 
		$html = (string)$this->setEscape('trim')->navigation()->menu()->renderMenu(
		    new Zend_Navigation(K111_Application_Module_Bootstrap::getDataNavigation()),
		    array(
		      'ulId' => 'main-menu',
		      'ulClass' => 'main-menu'
            )
		);
		echo ($html = str_replace(
		    array('[', ']'), 
		    array('<', '>'), 
		    $html
        ));
		
		$html = <<<inlineScript
(function($){
    $('#main-menu')
		.find('li:has("> ul")')
            .each(function(idx){
                $(this)
                    .addClass('sub-menu')
			     ;
            })
            .find('> a')
            	.attr({'data-ma-action' : 'submenu-toggle'})
            .end()
        .end()
    ;
})(jQuery);
inlineScript;
		$this->inlineScript()->appendScript($html);
		unset($html);
	?>
	<!-- /.main-menu -->
</aside>