<?php
/**
 * Script view: layout component # left_sidebar
 * @author khanhdtp
 */
?>
<!-- Left side column. contains the logo and sidebar -->
<aside id="sidebar" class="sidebar c-overflow">
	<!-- profile sub_sidebar -->
	<div class="s-profile">
        <a href="#" data-ma-action="profile-menu-toggle">
            <div class="sp-pic">
                <img src="<?php echo Default_Model_DbTable_Account::returnAvatarWebPath($this->authIdentity->avatar); ?>" alt="">
            </div>
            <div class="sp-info">
                <?php echo $this->authIdentity->fullname; ?>
                <small>[<?php echo $this->authIdentity->username; ?>]</small>
                <i class="zmdi zmdi-caret-down"></i>
            </div>
        </a>
        <ul class="main-menu">
            <li>
            	<?php
            		// View profile url
            		$url = $this->url(array(
            			'module' => 'default',
            			'controller' => 'account',
            			'action' => 'profile'
					), 'default', true);
            	?>
                <a href="<?php echo $url; ?>">
                	<i class="zmdi zmdi-face"></i> <?php echo $this->translate('Hồ sơ cá nhân'); ?>
                </a>
            </li>
            <li>
            	<?php
            		// Settings url
            		$url = $this->url(array(
            			'module' => 'default',
            			'controller' => 'account',
            			'action' => 'settings',
            			'_act' => 'edit'
					), 'default', true);
            	?>
                <a href="<?php echo $url; ?>">
                	<i class="zmdi zmdi-settings"></i> <?php echo $this->translate('Cài đặt khác'); ?>
                </a>
            </li>
            <li>
            	<?php
            		// Logout url
            		$url = $this->url(array(
            			'module' => 'default',
            			'controller' => 'account',
            			'action' => 'logout'
					), 'default', true);
            	?>
                <a href="<?php echo $url; ?>">
                	<i class="zmdi zmdi-time-restore"></i> <?php echo $this->translate('Đăng xuất'); ?>
				</a>
            </li>
        </ul>
    </div>
    <!-- ./profile sub_sidebar -->

	<!-- Sidebar Menu -->
	<?php 
		$html = (string)$this->setEscape('trim')->navigation()->menu()->renderMenu(
		    new Zend_Navigation(K111_Application_Module_Bootstrap::getDataNavigation()),
		    array(
		      'ulId' => 'main-menu',
		      'ulClass' => 'main-menu'
            )
		);
		echo ($html = str_replace(
		    array('[', ']'), 
		    array('<', '>'), 
		    $html
        ));
		
		$html = <<<inlineScript
(function($){
    $('#main-menu')
		.find('li:has("> ul")')
            .each(function(idx){
                $(this)
                    .addClass('sub-menu')
			     ;
            })
            .find('> a')
            	.attr({'data-ma-action' : 'submenu-toggle'})
            .end()
        .end()
    ;
})(jQuery);
inlineScript;
		$this->inlineScript()->appendScript($html);
		unset($html);
	?>
	<!-- /.main-menu -->
</aside>