<?php
/**
 * Script view: layout component # left_sidebar
 * @author khanhdtp
 */
?>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">

		<!-- Sidebar user panel (optional) -->
		<div class="user-panel hidden">
			<div class="pull-left image">
				<img src="/assets/backend/default/img/user2-160x160.jpg"
					class="img-circle" alt="User Image">
			</div>
			<div class="pull-left info">
				<p>Alexander Pierce</p>
				<!-- Status -->
				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>

		<!-- search form (Optional) -->
		<form action="#" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control"
					placeholder="Search..."> <span class="input-group-btn">
					<button type="submit" name="search" id="search-btn"
						class="btn btn-flat">
						<i class="fa fa-search"></i>
					</button>
				</span>
			</div>
		</form>
		<!-- /.search form -->

		<!-- Sidebar Menu -->
		<?php 
    		$html = (string)$this->setEscape('trim')->navigation()->menu()->renderMenu(
    		    new Zend_Navigation(K111_Application_Module_Bootstrap::getDataNavigation()),
    		    array(
    		      'ulId' => 'sidebar-menu',
    		      'ulClass' => 'sidebar-menu'
                )
    		);
    		echo ($html = str_replace(
    		    array('[', ']'), 
    		    array('<', '>'), 
    		    $html
            ));
    		
    		$html = <<<inlineScript
(function($){
    $('#sidebar-menu')
	// 
        .find('span.li-header')
            .each(function(idx){
                $(this).parent('li').addClass('header');
            })
        .end()
    // 
        .find('li:has("> ul")')
            .each(function(idx){
                $(this)
                    .addClass('treeview')
					.find('> ul')
					    .addClass('treeview-menu')
					.end()
			     ;
            })
        .end()
    ;
})(jQuery);
inlineScript;
    		$this->inlineScript()->appendScript($html);
    		unset($html);
		?>
		<!-- /.sidebar-menu -->
	</section>
	<!-- /.sidebar -->
</aside>