<?php
/**
 * Layout script: layout component # breadcrums
 * @author khanhdtp 2016-06-26
 */
?>
<!-- Breadcrumb -->
<?php 
	$html = (string)$this->setEscape('trim')->navigation()->breadcrumbs()
        ->setSeparator('</li><li>')
        ->setLinkLast(true)
		->render(
		    new Zend_Navigation(K111_Application_Module_Bootstrap::getDataNavigation()),
		    array()
		)
    ;
	$html = trim(str_replace(
	    array('[', ']'), 
	    array('<', '>'), 
	    $html
    ));
	echo $html ? "<ol class=\"breadcrumb\"><li>{$html}</li></ol>" : '';
	// Unset data; 
	unset($html);
?>
<!-- ./Breadcrumb -->