<?php
/**
 * Layout script: layout component # toolbars
 * @author khanhdtp 2016-06-26
 */
?>
<div class="clearfix toolbars-wrapper">
    <nav class="navbar navbar-default">
    	<div class="container-fluid">
    
    		<!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    			<ul class="nav navbar-nav navbar-right">
    				<?php echo $this->Bt3NavLinks(); ?>
    			</ul>
    		</div>
    		<!-- /.navbar-collapse -->
    	</div>
    	<!-- /.container-fluid -->
    </nav>
</div>