<?php
/**
 * Script view: post # crud
 * @author khanhdtp
 */
// Get K111_AssetsFinder
$assetsFinder = K111_AssetsFinder::getInstance();

// Toolbars
$this->Bt3NavLinks(array(
	$this->contOpts['isActUpdate'] ? $this->Bt3NavLinks()->iconApply() : '', 
    !$this->contOpts['isActDetail'] ? $this->Bt3NavLinks()->iconSaveAndNew() : '',
    !$this->contOpts['isActDetail'] ? $this->Bt3NavLinks()->iconSaveAndClose() : '',
    $this->contOpts['isActDetail'] ? $this->Bt3NavLinks()->iconNew() : '',
    $this->contOpts['isActDetail'] ? $this->Bt3NavLinks()->iconEdit() : '',
    $this->Bt3NavLinks()->iconClose()
));
?>
<div id="controller" class="card">
	<div class="card-body card-padding">
	<?php 
	    // Render form
	    echo $this->form;
	?>
	</div>
</div>
<?php
// CSS:
// +++ Inline style;
$this->HeadStyleAction($this->curRequest, null, array(
	'module' => 'default',
	'controller' => 'conf',
	'action' => 'crud'
));

// JS:
// +++ Lib: ckeditor
$this->headScript()->appendFile(
	$assetsFinder->files('ckeditor/ckeditor.js', 'lib'), null, array('minify_disabled' => true)
);
// +++ Inline script;
$this->HeadScriptAction($this->curRequest, null, array(
	'module' => 'default',
	'controller' => 'conf',
	'action' => 'crud'
));