<?php
/**
 * Script view: list product
 * @author khanhdtp
 */
// Get Zend_Controller_Front;
$front = Zend_Controller_Front::getInstance();

// Controller helpers
/* @var K111_Controller_Action_Helper_Common */
$commonHelper = $this->curController->getHelper('common');

// Toolbars
$this->Bt3NavLinks(array(
    $this->Bt3NavLinks()->iconNew(),
    $this->Bt3NavLinks()->iconDelete()
));
?>
<div id="controller" class="card">
	<!-- card-header -->
	<div class="card-header">
		<?php
			// Filter form;
			echo $this->Bt3FilterForm()->render($this->form, $this->formSearch);
		?><br/>
		<h2>
			<small><?php
			  	echo $this->translate('Tổng số dòng') . ': ' . ($totalItemsCount = $this->paginator->getTotalItemCount()) . '.';
			?></small>
		</h2>
	</div>
	<!-- ./card-header -->
	<form id="admin-form" class="card-body table-responsive" enctype="application/x-www-form-urlencoded" method="product" action="">
		<table id="tbl-data-list" class="table table-bordered table-condensed table-hover">
            <thead>
                <tr>
					<th width="10">#</th>
					<th width="10" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolCheckerToggler(); ?>
					</th>
					<th><?php echo $this->Bt3ManageTools()->mToolSorter($this->translate('Mã đơn hàng'), 'code'); ?></th>
					<th><?php echo $this->translate('Khách hàng'); ?></th>
					<th>
						<abbr title="<?php echo $this->translate('Hình thức thanh toán'); ?>">
							<?php echo $this->translate('H.T Thanh toán'); ?>
						</abbr>
					</th>
					<th>
						<abbr title="<?php echo $this->translate('Hình thức vận chuyển'); ?>">
							<?php echo $this->translate('H.T Vận chuyển'); ?>
						</abbr>
					</th>
					<th>
                   		<?php echo $this->translate('Gói quà'); ?>
                    </th>
                    <th>
                   		<?php echo $this->translate('Hóa đơn'); ?>
                    </th>
					<th>
                   		<?php echo $this->translate('Tổng tiền'); ?>
                    </th>
                    <th>
                   		<abbr title="<?php echo $this->translate('Trạng thái đơn hàng'); ?>">
                   			<?php echo $this->translate('T.Thái Đ.Hàng'); ?>
						</abbr>
                    </th>
                    <th>
                   		<abbr title="<?php echo $this->translate('Trạng thái xử lý'); ?>">
                   			<?php echo $this->translate('T.Thái X.lý'); ?>
						</abbr>
                    </th>
                    <th>
                    	<?php echo $this->translate('Ghi chú'); ?>
                    </th>
					<th width="10">
						<abbr title="<?php echo $this->translate('Quản lý'); ?>">
							<?php echo $this->translate('Q.Lý?'); ?>
						</abbr>
					</th>
				</tr>
            </thead>
            <tbody>
        <?php
            if ($totalItemsCount):
				// Manage tools 
				$manageBtnLinks = array(
					'detail' => $this->Bt3ManageTools()->mBtnDetail(),
					'edit' => $this->Bt3ManageTools()->mBtnEdit()
				);
				// Cart's options
				// +++ gift 
				$giftOpts = Product_Model_DbTable_Cart::returnGifts();
				// +++ invoice
				$invoiceOpts = Product_Model_DbTable_Cart::returnInvoices();
				// +++ payment methods
				$pmtMethodOpts = Product_Model_DbTable_Cart::returnPaymentMethods();
				// +++ transport methods
				$transportMethodOpts = Product_Model_DbTable_Cart::returnTransportMethods();
				// +++ status
				$statusOpts = Product_Model_DbTable_Cart::returnStatuses();
				// +++ process status
				$processStatusOpts = Product_Model_DbTable_Cart::returnProcessStatuses();
                //
                $no = 0;
                //
                foreach ($this->paginator as $item):
					// Creator
					$creatorEnt = $item->findParentCreator();
        ?>
				<tr>
					<td align="center" class="text-nowrap"><?php echo ++$no; ?></td>
					<td align="center" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolChecker($item->id); ?>
					</td>
					<td>
						<?php echo $item->code; ?>
					</td>
					<td>
						<?php echo $creatorEnt->fullname; ?>
					</td>
					<td>
						<?php echo $pmtMethodOpts[$item->payment_method]; ?>
					</td>
					<td>
						<?php echo $transportMethodOpts[$item->transport_method]; ?>
					</td>
					<td>
						<?php echo $giftOpts[$item->gift]; ?>
					</td>
					<td>
						<?php echo $invoiceOpts[$item->invoice]; ?>
					</td>
					<td>
						<?php echo $commonHelper->numberFormat($item->total_price); ?>
					</td>
					<td>
						<?php echo $statusOpts[$item->status]; ?>
					</td>
					<td>
						<?php echo $processStatusOpts[$item->process_status]; ?>
					</td>
					<td>
						<?php echo $item->note; ?>
					</td>
					<td class="text-nowrap">
					<?php
						$manageBtns = array(
							'__detail_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['detail']),
							'__update_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['edit']),
						);
						echo implode("\n", $manageBtns);
					?>
					</td>
				</tr>
        <?php 
                endforeach;
            endif;
        ?>
			</tbody>
		</table>
	</form>
	<!-- /.box-body -->
	<div class="card-header clearfix">
        <div class="pull-right">
            <?php
                echo $this->paginationControl($this->paginator); 
            ?>
        </div>
	</div>
</div>
<?php
// CSS:
// +++ Inline style;
$this->HeadStyleAction($this->curRequest, array(), array(
	'module' => 'product',
	'controller' => 'cart'
));

// CSS:
// +++ Inline script;
$this->HeadScriptAction($this->curRequest, array(), array(
	'module' => 'product',
	'controller' => 'cart'
));