<?php
/**
 * Script view: list product
 * @author khanhdtp
 */
// Get Zend_Controller_Front;
$front = Zend_Controller_Front::getInstance();

// Toolbars
$this->Bt3NavLinks(array(
    $this->Bt3NavLinks()->iconNew(),
    $this->Bt3NavLinks()->iconDelete()
));
?>
<div id="controller" class="card">
	<!-- card-header -->
	<div class="card-header">
		<?php
			// Filter form;
			echo $this->Bt3FilterForm()->render($this->form, $this->formSearch);
		?><br/>
		<h2>
			<small><?php
			  	echo $this->translate('Tổng số dòng') . ': ' . ($totalItemsCount = $this->paginator->getTotalItemCount()) . '.';
			?></small>
		</h2>
	</div>
	<!-- ./card-header -->
	<form id="admin-form" class="card-body table-responsive" enctype="application/x-www-form-urlencoded" method="product" action="">
		<table id="tbl-data-list" class="table table-bordered table-condensed table-hover">
            <thead>
                <tr>
					<th width="10">#</th>
					<th width="10" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolCheckerToggler(); ?>
					</th>
					<th><?php echo $this->Bt3ManageTools()->mToolSorter($this->translate('Tên sản phẩm'), 'name'); ?></th>
					<th width="10" class="text-nowrap"><?php echo $this->translate('Hình ảnh'); ?></th>
					<th><?php echo $this->translate('Ghi chú'); ?></th>
					<th><?php echo $this->translate('Danh mục'); ?></th>
					<th width="10">
                    	<abbr title="<?php echo $this->translate('Lượt xem'); ?>">
                    		<?php echo $this->translate('L.Xem?'); ?>
                    	</abbr>
                    </th>
                    <th width="10">
                    	<abbr title="<?php echo $this->translate('Kích hoạt?'); ?>">
                    		<?php echo $this->translate('K.Hoạt?'); ?>
                    	</abbr>
                    </th>
					<th width="10">
						<abbr title="<?php echo $this->translate('Quản lý'); ?>">
							<?php echo $this->translate('Q.Lý?'); ?>
						</abbr>
					</th>
				</tr>
            </thead>
            <tbody>
        <?php
            if ($totalItemsCount):
				// Manage tools 
				$manageBtnLinks = array(
					'lang' => $this->Bt3ManageTools()->mBtnLang(),
					'detail' => $this->Bt3ManageTools()->mBtnDetail(),
					'edit' => $this->Bt3ManageTools()->mBtnEdit(),
					'delete' => $this->Bt3ManageTools()->mBtnDelete(),
				);
                //
                $no = 0;
                //
                foreach ($this->paginator as $item):
					// Available languages
					$availLangs = (array)array_keys($item->findChildrenEntry());
					
					// Categories
					$categoryEntitiesByProduct = (array)$item->findChildrenProductCategory();
					$itemCateOpts = array_intersect_key((array)$this->cateOpts, $categoryEntitiesByProduct);
					// +++ 
					$categoryHtml = empty($itemCateOpts) ? '' : (
						'<ol><li>' 
							. implode('</li><li>', $itemCateOpts)
						. '</li></ol>' 
					);
					// +++ 
					unset($categoryEntitiesByProduct); 
        ?>
				<tr>
					<td align="center" class="text-nowrap"><?php echo ++$no; ?></td>
					<td align="center" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolChecker($item->id); ?>
					</td>
					<td>
						<div class="clearfix lang-icons lang-icons-16">
							<?php echo Language::renderLangIcons($availLangs); ?>
						</div>
						<?php echo $item->name; ?><br/>
						<small class="m-l-10"><i>[<?php echo $item->alias; ?>]</i></small>
					</td>
					<td align="center" class="text-nowrap">
					<?php 
						// Images
						$imgs = (array)$item->returnImgsWebPath();
						$firstImg = trim($imgs[0]);
						if ($firstImg):
					?>
						<a class="gallery-popup-trigger" href="#" data-imgs="<?php echo empty($imgs) ? '[]' : htmlspecialchars(json_encode($imgs)); ?>">
							<img src="<?php echo htmlspecialchars($firstImg); ?>" class="img-thumb img-thumb-64" />
						</a>
					<?php
							unset($firstImg); 
						endif; 
					?>
					</td>
					<td><?php echo $item->note; ?></td>
					<td>
					<?php
						if (!empty($itemCateOpts)):
							// Case: has multi category
							if (($count = count($itemCateOpts)) > 1):
					?>
						<a class="a-popover" title="<?php echo $this->translate('Danh mục'); ?>" data-placement="top" data-html="true" data-content="<?php echo htmlspecialchars($categoryHtml) ?>" href="javascript:void(0);">
							<i class="glyphicon glyphicon-list"></i> <?php echo current($itemCateOpts) . ('...(' . $count . ')')  ?>
						</a>
					<?php 
							else:
					?>
						<span><?php echo current($itemCateOpts); ?></span>
					<?php
							endif;
							unset($count);
						endif; 
					?>
					</td>
					<td align="center" class="text-nowrap">
						<?php echo number_format((int)$item->viewed); ?>
					</td>
					<td align="center" class="text-nowrap">
						<?php echo $this->Bt3ManageTools()->mToolActiveToggler($item->id, $item->active); ?>
					</td>
					<td class="text-nowrap">
					<?php
						$manageBtns = array(
							'__lang_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['lang']),
							'__detail_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['detail']),
							'__update_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['edit']),
							'__delete_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['delete'])
						);
						echo implode("\n", $manageBtns);
					?>
					</td>
				</tr>
        <?php 
                endforeach;
            endif;
        ?>
			</tbody>
		</table>
	</form>
	<!-- /.box-body -->
	<div class="card-header clearfix">
        <div class="pull-right">
            <?php
                echo $this->paginationControl($this->paginator); 
            ?>
        </div>
	</div>
</div>
<?php
// CSS:
// +++ Inline style;
$this->HeadStyleAction($this->curRequest, array(), array(
	'module' => 'product',
	'controller' => 'index'
));

// CSS:
// +++ Inline script;
$this->HeadScriptAction($this->curRequest, array(), array(
	'module' => 'product',
	'controller' => 'index'
));