<?php
/**
 * Script view: list group 
 * @author khanhdtp
 */
// Get Zend_Controller_Front;
$front = Zend_Controller_Front::getInstance();

// Set page's title
$this->layout()->pageTitle = $this->translate('Danh mục nhóm tài khoản');

// Toolbars
$this->Bt3NavLinks(array(
    $this->Bt3NavLinks()->iconNew(),
    $this->Bt3NavLinks()->iconDelete()
));

// Filter form;
echo $this->Bt3FilterForm()->render($this->form, $this->formSearch);
?>
<div class="box">
	<div class="box-header">
		<div class="box-title"><span class="label label-info"><?php
		  echo $this->translate('Tổng số dòng') . ': ' . ($totalItemsCount = count($this->paginator)) . '.' 
		?></span></div>
	</div>
	<!-- /.box-header -->
	<div class="box-body no-padding table-responsive">
		<table id="tbl-data-list" class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
					<th width="10">No.</th>
					<th width="10" class="text-center">
						<?php echo $this->Bt3ManageTools()->mToolCheckerToggler(); ?>
					</th>
					<th><?php echo $this->translate('Mã nhóm tài khoản'); ?></th>
					<th><?php echo $this->translate('Tên nhóm tài khoản'); ?></th>
					<th><?php echo $this->translate('Ghi chú'); ?></th>
                    <th width="10"><?php echo $this->translate('K.Hoạt?'); ?></th>
					<th width="10"><?php echo $this->translate('Q.Lý?'); ?></th>
				</tr>
            </thead>
            <tbody>
        <?php
            if ($totalItemsCount):
				// Manage tools 
				$manageBtnLinks = array(
					'detail' => $this->Bt3ManageTools()->mBtnDetail(),
					'edit' => $this->Bt3ManageTools()->mBtnEdit(),
					'delete' => $this->Bt3ManageTools()->mBtnDelete(),
				);
                //
                $no = 0;
                //
                foreach ($this->paginator as $item):
        ?>
				<tr>
					<td align="center" class="nowrap"><?php echo ++$no; ?></td>
					<td align="center" class="nowrap">
						<?php echo $this->Bt3ManageTools()->mToolChecker($item->id); ?>
					</td>
					<td><?php echo $item->code; ?></td>
					<td><?php echo $item->name; ?></td>
					<td><?php echo $item->note; ?></td>
					<td align="center" class="nowrap"><?php echo $this->Bt3ManageTools()->mBtnActiveToggler($item->active); ?></td>
					<td class="nowrap">
					<?php
						$manageBtns = array(
							'__detail_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['detail']),
							'__update_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['edit']),
							'__delete_' => str_replace(array('__id__'), array($item->id), $manageBtnLinks['delete'])
						);
						echo implode("\n", $manageBtns);
					?>
					</td>
				</tr>
        <?php 
                endforeach;
            endif;
        ?>
			</tbody>
		</table>
	</div>
	<!-- /.box-body -->
	<div class="box-footer clearfix">
        <div class="pull-right">
            <?php
                echo $this->paginationControl($this->paginator); 
            ?>
        </div>
	</div>
</div>
<?php
// CSS:
// +++ Inline style;
$inlineStyle = <<<inlineStyle
inlineStyle;
// +++
$this->HeadStyle()->appendStyle($inlineStyle, array(
    'media' => 'all'
));
unset($inlineStyle);

// CSS:
// +++ Inline script;
$inlineScript = <<<inlineScript
(function($){
    
})(jQuery);
inlineScript;
// +++
$this->InlineScript()->appendScript($inlineScript);
unset($inlineScript);