<?php
/**
 * Script view: login
 * @author khanhdtp
 */
// Get Zend_Controller_Front;
$front = Zend_Controller_Front::getInstance();

// Load layout's component: message
$this->action('layout', $front->getDefaultControllerName(), $front->getDefaultModule(), array(
    'components' => array('messages' => '')
));

// Set page's title
$this->layout()->pageTitle = $this->translate('Đăng nhập hệ thống');
?>
<div id="frm-container" class="container">
    <!-- form start -->
	<form id="frm-login" class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
        <input type="hidden" id="security" name="security" value="<?php echo $this->security; ?>" >
		<div class="box-body">
			<div class="form-group">
				<label for="username" class="col-sm-2 control-label"><?php echo $this->translate('Tên đăng nhập'); ?></label>
				<div class="col-sm-10">
					<input type="text" maxlength="250" class="form-control" 
					  id="username" name="username" required="required" 
					  placeholder="<?php echo $this->translate('Nhập tên đăng nhập'); ?>"
					  value="<?php echo htmlspecialchars($_POST['username']); ?>"
                    />
				</div>
			</div>
			<div class="form-group">
				<label for="password" class="col-sm-2 control-label"><?php echo $this->translate('Mật khẩu'); ?></label>
				<div class="col-sm-10">
					<input type="password" maxlength="50" class="form-control" 
					  id="password" name="password" required="required" 
					  placeholder="<?php echo $this->translate('Nhập mật khẩu'); ?>"
					  value="<?php echo htmlspecialchars($_POST['password']); ?>"
					/>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<div class="checkbox">
						<label><input type="checkbox" id="remember" name="remember" <?php echo $_POST['remember'] ? 'checked="checked"' : ''; ?> > Remember me</label>
					</div>
				</div>
			</div>
			<div class="form-group">
				<button type="reset" class="btn btn-default"><?php echo $this->translate('Nhập lại'); ?></button>
				<button type="submit" class="btn btn-info pull-right"><?php echo $this->translate('Đăng nhập'); ?></button>
			</div>
		</div>
		<!-- /.box-body -->
	</form>
</div>

<?php
// CSS:
// +++ Inline style;
$inlineStyle = <<<inlineStyle
inlineStyle;
// +++
$this->HeadStyle()->appendStyle($inlineStyle, array(
    'media' => 'all'
));
unset($inlineStyle);

// CSS:
// +++ Inline script;
$inlineScript = <<<inlineScript
(function($){
    
})(jQuery);
inlineScript;
// +++
$this->InlineScript()->appendScript($inlineScript);
unset($inlineScript);