<?php
/**
 * 
 */
// Get Zend_Controller_Front;
$front = Zend_Controller_Front::getInstance();
// Flag: is in production mode?
$isEnvProduction = $front->getParam('isEnvProduction');
// Assets minify string;
$assetsMinStr = $isEnvProduction ? '.min' : '';  

// Get K111_AssetsFinder;
$assetsFinder = K111_AssetsFinder::getInstance();

// Load layout's components
$this->action('layout', $front->getDefaultControllerName(), $front->getDefaultModule(), array());
?>
<!DOCTYPE html>
<html>
<head>
<?php 
// Meta
$headMeta = <<<HeadMeta
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
HeadMeta;
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->HeadMeta()
	->appendName('keywords', 'website keywords')
	->appendName('description', 'website description')
	->appendName('viewport', 'width=device-width, initial-scale=1')
	->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
;
echo $this->HeadMeta() . "\n{$headMeta}\n";
unset($headMeta);
// Title
$this->HeadTitle("{$_SERVER['SERVER_NAME']}")
	->setSeparator(' / ')
;
echo $this->HeadTitle() . "\n";

// Headlink
$this->HeadLink()
// +++ Vendor CSS
    ->appendStylesheet($assetsFinder->files("bower_components/animate.css/animate.min.css", 'lib'))
	->appendStylesheet($assetsFinder->files("bower_components/sweetalert/dist/sweetalert.css", 'lib'))
	->appendStylesheet($assetsFinder->files("bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css", 'lib'))
	->appendStylesheet($assetsFinder->files("bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css", 'lib'))
// +++ Material Admin
    ->appendStylesheet($assetsFinder->files("MALight_1.min.css", 'css'))
    ->appendStylesheet($assetsFinder->files("MALight_2.min.css", 'css'))
// +++ Project's css
    ->appendStylesheet($assetsFinder->files("style{$assetsMinStr}.css", 'css'))
;
echo $this->HeadLink();

// HeadStyle # inline style;
// +++ 
$msViewport = <<<HeadStyle
	@-ms-viewport{
	  width: device-width;
	}
HeadStyle;
// +++ 
echo $this->HeadStyle()->appendStyle($msViewport, array(
    'media' => 'all'
));
unset($msViewport);
?>
</head>
<body class="clearfix">
	<?php 
        // Component: header;
        echo $this->layout()->components['header'];
    ?>
	<section id="main">
	    <?php 
	        // Component: left sidebar;
	        echo $this->layout()->components['left_sidebar'];
	        // Component: control sidebar;
	        echo $this->layout()->components['right_sidebar'];
            // Component: page header, +breadcrumb;
            echo $this->layout()->components['breadcrumb'];
        ?>
	    <!-- Main content -->
		<section id="content" class="clearfix">
            <?php
                // Component: page's messages;
                echo $this->layout()->components['messages'];
                // Component: page's messages;
                echo $this->layout()->components['toolbars'];
            ?>
            <div id="body-wrapper" class="m-t-30">
	            <?php
	                // Page's content;
	                echo $this->layout()->content;
	            ?>
			</div>
            <?php
                // Component: page's messages;
                echo $this->layout()->components['toolbars'];
            ?>
        </section>
		<!-- /.content -->
    </section>
    <?php 
        // Component: footer;
        echo $this->layout()->components['footer'];
    ?>
    <!-- ./wrapper -->
    
    <!-- Page Loader -->
    <div class="page-loader">
        <div class="preloader pls-blue">
            <svg class="pl-circular" viewBox="25 25 50 50">
                <circle class="plc-path" cx="50" cy="50" r="20" />
            </svg>
            <p>Please wait...</p>
        </div>
    </div>
<?php 
// HeadScript
$this->HeadScript()
// +++ jQuery
    ->appendFile($assetsFinder->files("bower_components/jquery/dist/jquery.min.js", 'lib'))
// +++ Bootstrap
    ->appendFile($assetsFinder->files("bower_components/bootstrap/dist/js/bootstrap.min.js", 'lib'))

// +++ HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
// +++ WARNING: Respond.js doesn't work if you view the page via file://
    ->appendFile($assetsFinder->files("html5shiv/html5shiv-3.7.3{$assetsMinStr}.js", 'js'), 'if lt IE 9')
    ->appendFile($assetsFinder->files("respond/respond-1.4.2{$assetsMinStr}.js", 'js'), 'if lt IE 9')
// +++ Material Admin
	->appendFile($assetsFinder->files("bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js", 'lib')) 
    ->appendFile($assetsFinder->files("bower_components/Waves/dist/waves.min.js", 'lib'))
	->appendFile($assetsFinder->files("bootstrap-growl/bootstrap-growl.min.js", 'lib'))
	->appendFile($assetsFinder->files("bower_components/sweetalert/dist/sweetalert.min.js", 'lib'))
// +++ project's main file
	->appendFile($assetsFinder->files("MALight.min.js", 'js'))
    ->appendFile($assetsFinder->files("script{$assetsMinStr}.js", 'js'))
;
echo $this->HeadScript();

// InlineScript # inline script;
echo $this->InlineScript();
?>
</body>
</html>