<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
    	<tr>
    		<th colspan="100">
    			<div class="block-header">
				    <ul class="actions">
				        <li>
				            <a href="#">
				                <i class="zmdi zmdi-trending-up"></i>
				            </a>
				        </li>
				        <li>
				            <a href="#">
				                <i class="zmdi zmdi-check-all"></i>
				            </a>
				        </li>
				        <li class="dropdown">
				            <a href="#" data-toggle="dropdown">
				                <i class="zmdi zmdi-more-vert"></i>
				            </a>
				
				            <ul class="dropdown-menu dropdown-menu-right">
				                <li>
				                    <a href="#">Refresh</a>
				                </li>
				                <li>
				                    <a href="#">Manage Widgets</a>
				                </li>
				                <li>
				                    <a href="#">Widgets Settings</a>
				                </li>
				            </ul>
				        </li>
				    </ul>
				
				</div>
    		</th>
    	</tr>
	    <tr>
	        <th>#</th>
	        <th>First Name</th>
	        <th>Last Name</th>
	        <th>Username</th>
	        <th>Nickname</th>
	    </tr>
    </thead>
    <tbody>
    <tr class="active">
        <td>1</td>
        <td>Alexandra</td>
        <td>Christopher</td>
        <td>@makinton</td>
        <td>Ducky</td>
    </tr>
    <tr class="info">
        <td>3</td>
        <td>Sebastian</td>
        <td>Johnston</td>
        <td>@sebastian</td>
        <td>Jaycee</td>
    </tr>
    <tr class="warning c-white">
        <td>4</td>
        <td>Mitchell</td>
        <td>Christin</td>
        <td>@mitchell4u</td>
        <td>AdskiDeAnus</td>
    </tr>
    <tr class="success c-white">
        <td>2</td>
        <td>Madeleine</td>
        <td>Hollaway</td>
        <td>@hollway</td>
        <td>Cheese</td>
    </tr>
    <tr class="danger c-white">
        <td>5</td>
        <td>Elizabeth</td>
        <td>Belkitt</td>
        <td>@belkitt</td>
        <td>Goat</td>
    </tr>
    </tbody>
</table>